### ISSUE TITLE
CHOICE 1 的按钮点击后进入github,没有使用脚本

### ISSUE THREAD

**Issue by wzqvip** [eastpiger/Course-Table-ICS-Formatter#6]
从eams界面的地址栏用javascript方法是可以的,但是把介绍里面的按钮拖到收藏夹之后,从eams点击就会进入 https://github.com/eastpiger/Course-Table-ICS-Formatter/blob/master/installbutton.png

**Comment by wtlyu** [comment]
你需要从这个url拖
https://eastpiger.github.io/Course-Table-ICS-Formatter/

**Comment by wtlyu** [comment]
https://wtlyu.github.io/Course-Table-ICS-Formatter/
新版本是这个
